// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.0
// source: pkg/proto/block.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Block struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ProposalId     string                 `protobuf:"bytes,1,opt,name=proposal_id,json=proposalId,proto3" json:"proposal_id,omitempty"`
	ProposerId     string                 `protobuf:"bytes,2,opt,name=proposer_id,json=proposerId,proto3" json:"proposer_id,omitempty"`
	Transactions   []*Transaction         `protobuf:"bytes,3,rep,name=transactions,proto3" json:"transactions,omitempty"`
	Timestamp      *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Hash           string                 `protobuf:"bytes,5,opt,name=hash,proto3" json:"hash,omitempty"`
	Height         uint64                 `protobuf:"varint,6,opt,name=height,proto3" json:"height,omitempty"`
	PrevHash       string                 `protobuf:"bytes,7,opt,name=prev_hash,json=prevHash,proto3" json:"prev_hash,omitempty"`
	NextValidators []*ValidatorInfo       `protobuf:"bytes,8,rep,name=next_validators,json=nextValidators,proto3" json:"next_validators,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Block) Reset() {
	*x = Block{}
	mi := &file_pkg_proto_block_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Block) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Block) ProtoMessage() {}

func (x *Block) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_block_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Block.ProtoReflect.Descriptor instead.
func (*Block) Descriptor() ([]byte, []int) {
	return file_pkg_proto_block_proto_rawDescGZIP(), []int{0}
}

func (x *Block) GetProposalId() string {
	if x != nil {
		return x.ProposalId
	}
	return ""
}

func (x *Block) GetProposerId() string {
	if x != nil {
		return x.ProposerId
	}
	return ""
}

func (x *Block) GetTransactions() []*Transaction {
	if x != nil {
		return x.Transactions
	}
	return nil
}

func (x *Block) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *Block) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *Block) GetHeight() uint64 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *Block) GetPrevHash() string {
	if x != nil {
		return x.PrevHash
	}
	return ""
}

func (x *Block) GetNextValidators() []*ValidatorInfo {
	if x != nil {
		return x.NextValidators
	}
	return nil
}

type PreBlockProposal struct {
	state           protoimpl.MessageState  `protogen:"open.v1"`
	ProposalId      string                  `protobuf:"bytes,1,opt,name=proposal_id,json=proposalId,proto3" json:"proposal_id,omitempty"`
	ProposerId      string                  `protobuf:"bytes,2,opt,name=proposer_id,json=proposerId,proto3" json:"proposer_id,omitempty"`
	Transactions    []*Transaction          `protobuf:"bytes,3,rep,name=transactions,proto3" json:"transactions,omitempty"`
	Height          uint64                  `protobuf:"varint,4,opt,name=height,proto3" json:"height,omitempty"`
	PrevHash        string                  `protobuf:"bytes,5,opt,name=prev_hash,json=prevHash,proto3" json:"prev_hash,omitempty"`
	RawTransactions map[string]*Transaction `protobuf:"bytes,6,rep,name=raw_transactions,json=rawTransactions,proto3" json:"raw_transactions,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PreBlockProposal) Reset() {
	*x = PreBlockProposal{}
	mi := &file_pkg_proto_block_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PreBlockProposal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PreBlockProposal) ProtoMessage() {}

func (x *PreBlockProposal) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_block_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PreBlockProposal.ProtoReflect.Descriptor instead.
func (*PreBlockProposal) Descriptor() ([]byte, []int) {
	return file_pkg_proto_block_proto_rawDescGZIP(), []int{1}
}

func (x *PreBlockProposal) GetProposalId() string {
	if x != nil {
		return x.ProposalId
	}
	return ""
}

func (x *PreBlockProposal) GetProposerId() string {
	if x != nil {
		return x.ProposerId
	}
	return ""
}

func (x *PreBlockProposal) GetTransactions() []*Transaction {
	if x != nil {
		return x.Transactions
	}
	return nil
}

func (x *PreBlockProposal) GetHeight() uint64 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *PreBlockProposal) GetPrevHash() string {
	if x != nil {
		return x.PrevHash
	}
	return ""
}

func (x *PreBlockProposal) GetRawTransactions() map[string]*Transaction {
	if x != nil {
		return x.RawTransactions
	}
	return nil
}

type PreBlockAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProposalId    string                 `protobuf:"bytes,1,opt,name=proposal_id,json=proposalId,proto3" json:"proposal_id,omitempty"`
	ValidatorId   string                 `protobuf:"bytes,2,opt,name=validator_id,json=validatorId,proto3" json:"validator_id,omitempty"`
	ValidatorSig  []byte                 `protobuf:"bytes,3,opt,name=validator_sig,json=validatorSig,proto3" json:"validator_sig,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PreBlockAck) Reset() {
	*x = PreBlockAck{}
	mi := &file_pkg_proto_block_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PreBlockAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PreBlockAck) ProtoMessage() {}

func (x *PreBlockAck) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_block_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PreBlockAck.ProtoReflect.Descriptor instead.
func (*PreBlockAck) Descriptor() ([]byte, []int) {
	return file_pkg_proto_block_proto_rawDescGZIP(), []int{2}
}

func (x *PreBlockAck) GetProposalId() string {
	if x != nil {
		return x.ProposalId
	}
	return ""
}

func (x *PreBlockAck) GetValidatorId() string {
	if x != nil {
		return x.ValidatorId
	}
	return ""
}

func (x *PreBlockAck) GetValidatorSig() []byte {
	if x != nil {
		return x.ValidatorSig
	}
	return nil
}

type BlockShred struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BlockHash     string                 `protobuf:"bytes,1,opt,name=block_hash,json=blockHash,proto3" json:"block_hash,omitempty"`
	TotalShreds   int32                  `protobuf:"varint,2,opt,name=total_shreds,json=totalShreds,proto3" json:"total_shreds,omitempty"`
	ShredIndex    int32                  `protobuf:"varint,3,opt,name=shred_index,json=shredIndex,proto3" json:"shred_index,omitempty"`
	Data          []byte                 `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlockShred) Reset() {
	*x = BlockShred{}
	mi := &file_pkg_proto_block_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockShred) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockShred) ProtoMessage() {}

func (x *BlockShred) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_block_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockShred.ProtoReflect.Descriptor instead.
func (*BlockShred) Descriptor() ([]byte, []int) {
	return file_pkg_proto_block_proto_rawDescGZIP(), []int{3}
}

func (x *BlockShred) GetBlockHash() string {
	if x != nil {
		return x.BlockHash
	}
	return ""
}

func (x *BlockShred) GetTotalShreds() int32 {
	if x != nil {
		return x.TotalShreds
	}
	return 0
}

func (x *BlockShred) GetShredIndex() int32 {
	if x != nil {
		return x.ShredIndex
	}
	return 0
}

func (x *BlockShred) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type ValidatorInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PeerId        string                 `protobuf:"bytes,1,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	TotalStake    uint64                 `protobuf:"varint,2,opt,name=total_stake,json=totalStake,proto3" json:"total_stake,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidatorInfo) Reset() {
	*x = ValidatorInfo{}
	mi := &file_pkg_proto_block_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidatorInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidatorInfo) ProtoMessage() {}

func (x *ValidatorInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_block_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidatorInfo.ProtoReflect.Descriptor instead.
func (*ValidatorInfo) Descriptor() ([]byte, []int) {
	return file_pkg_proto_block_proto_rawDescGZIP(), []int{4}
}

func (x *ValidatorInfo) GetPeerId() string {
	if x != nil {
		return x.PeerId
	}
	return ""
}

func (x *ValidatorInfo) GetTotalStake() uint64 {
	if x != nil {
		return x.TotalStake
	}
	return 0
}

type ValidatorSetUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Validators    map[string]uint64      `protobuf:"bytes,1,rep,name=validators,proto3" json:"validators,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	Source        string                 `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidatorSetUpdate) Reset() {
	*x = ValidatorSetUpdate{}
	mi := &file_pkg_proto_block_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidatorSetUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidatorSetUpdate) ProtoMessage() {}

func (x *ValidatorSetUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_block_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidatorSetUpdate.ProtoReflect.Descriptor instead.
func (*ValidatorSetUpdate) Descriptor() ([]byte, []int) {
	return file_pkg_proto_block_proto_rawDescGZIP(), []int{5}
}

func (x *ValidatorSetUpdate) GetValidators() map[string]uint64 {
	if x != nil {
		return x.Validators
	}
	return nil
}

func (x *ValidatorSetUpdate) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *ValidatorSetUpdate) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

var File_pkg_proto_block_proto protoreflect.FileDescriptor

const file_pkg_proto_block_proto_rawDesc = "" +
	"\n" +
	"\x15pkg/proto/block.proto\x12\x05proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bpkg/proto/transaction.proto\"\xc3\x02\n" +
	"\x05Block\x12\x1f\n" +
	"\vproposal_id\x18\x01 \x01(\tR\n" +
	"proposalId\x12\x1f\n" +
	"\vproposer_id\x18\x02 \x01(\tR\n" +
	"proposerId\x126\n" +
	"\ftransactions\x18\x03 \x03(\v2\x12.proto.TransactionR\ftransactions\x128\n" +
	"\ttimestamp\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x12\n" +
	"\x04hash\x18\x05 \x01(\tR\x04hash\x12\x16\n" +
	"\x06height\x18\x06 \x01(\x04R\x06height\x12\x1b\n" +
	"\tprev_hash\x18\a \x01(\tR\bprevHash\x12=\n" +
	"\x0fnext_validators\x18\b \x03(\v2\x14.proto.ValidatorInfoR\x0enextValidators\"\xf2\x02\n" +
	"\x10PreBlockProposal\x12\x1f\n" +
	"\vproposal_id\x18\x01 \x01(\tR\n" +
	"proposalId\x12\x1f\n" +
	"\vproposer_id\x18\x02 \x01(\tR\n" +
	"proposerId\x126\n" +
	"\ftransactions\x18\x03 \x03(\v2\x12.proto.TransactionR\ftransactions\x12\x16\n" +
	"\x06height\x18\x04 \x01(\x04R\x06height\x12\x1b\n" +
	"\tprev_hash\x18\x05 \x01(\tR\bprevHash\x12W\n" +
	"\x10raw_transactions\x18\x06 \x03(\v2,.proto.PreBlockProposal.RawTransactionsEntryR\x0frawTransactions\x1aV\n" +
	"\x14RawTransactionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12(\n" +
	"\x05value\x18\x02 \x01(\v2\x12.proto.TransactionR\x05value:\x028\x01\"v\n" +
	"\vPreBlockAck\x12\x1f\n" +
	"\vproposal_id\x18\x01 \x01(\tR\n" +
	"proposalId\x12!\n" +
	"\fvalidator_id\x18\x02 \x01(\tR\vvalidatorId\x12#\n" +
	"\rvalidator_sig\x18\x03 \x01(\fR\fvalidatorSig\"\x83\x01\n" +
	"\n" +
	"BlockShred\x12\x1d\n" +
	"\n" +
	"block_hash\x18\x01 \x01(\tR\tblockHash\x12!\n" +
	"\ftotal_shreds\x18\x02 \x01(\x05R\vtotalShreds\x12\x1f\n" +
	"\vshred_index\x18\x03 \x01(\x05R\n" +
	"shredIndex\x12\x12\n" +
	"\x04data\x18\x04 \x01(\fR\x04data\"I\n" +
	"\rValidatorInfo\x12\x17\n" +
	"\apeer_id\x18\x01 \x01(\tR\x06peerId\x12\x1f\n" +
	"\vtotal_stake\x18\x02 \x01(\x04R\n" +
	"totalStake\"\xf0\x01\n" +
	"\x12ValidatorSetUpdate\x12I\n" +
	"\n" +
	"validators\x18\x01 \x03(\v2).proto.ValidatorSetUpdate.ValidatorsEntryR\n" +
	"validators\x12\x16\n" +
	"\x06source\x18\x02 \x01(\tR\x06source\x128\n" +
	"\ttimestamp\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x1a=\n" +
	"\x0fValidatorsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x04R\x05value:\x028\x01B\x15Z\x13grapthway/pkg/protob\x06proto3"

var (
	file_pkg_proto_block_proto_rawDescOnce sync.Once
	file_pkg_proto_block_proto_rawDescData []byte
)

func file_pkg_proto_block_proto_rawDescGZIP() []byte {
	file_pkg_proto_block_proto_rawDescOnce.Do(func() {
		file_pkg_proto_block_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_proto_block_proto_rawDesc), len(file_pkg_proto_block_proto_rawDesc)))
	})
	return file_pkg_proto_block_proto_rawDescData
}

var file_pkg_proto_block_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_pkg_proto_block_proto_goTypes = []any{
	(*Block)(nil),                 // 0: proto.Block
	(*PreBlockProposal)(nil),      // 1: proto.PreBlockProposal
	(*PreBlockAck)(nil),           // 2: proto.PreBlockAck
	(*BlockShred)(nil),            // 3: proto.BlockShred
	(*ValidatorInfo)(nil),         // 4: proto.ValidatorInfo
	(*ValidatorSetUpdate)(nil),    // 5: proto.ValidatorSetUpdate
	nil,                           // 6: proto.PreBlockProposal.RawTransactionsEntry
	nil,                           // 7: proto.ValidatorSetUpdate.ValidatorsEntry
	(*Transaction)(nil),           // 8: proto.Transaction
	(*timestamppb.Timestamp)(nil), // 9: google.protobuf.Timestamp
}
var file_pkg_proto_block_proto_depIdxs = []int32{
	8, // 0: proto.Block.transactions:type_name -> proto.Transaction
	9, // 1: proto.Block.timestamp:type_name -> google.protobuf.Timestamp
	4, // 2: proto.Block.next_validators:type_name -> proto.ValidatorInfo
	8, // 3: proto.PreBlockProposal.transactions:type_name -> proto.Transaction
	6, // 4: proto.PreBlockProposal.raw_transactions:type_name -> proto.PreBlockProposal.RawTransactionsEntry
	7, // 5: proto.ValidatorSetUpdate.validators:type_name -> proto.ValidatorSetUpdate.ValidatorsEntry
	9, // 6: proto.ValidatorSetUpdate.timestamp:type_name -> google.protobuf.Timestamp
	8, // 7: proto.PreBlockProposal.RawTransactionsEntry.value:type_name -> proto.Transaction
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_pkg_proto_block_proto_init() }
func file_pkg_proto_block_proto_init() {
	if File_pkg_proto_block_proto != nil {
		return
	}
	file_pkg_proto_transaction_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_proto_block_proto_rawDesc), len(file_pkg_proto_block_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_proto_block_proto_goTypes,
		DependencyIndexes: file_pkg_proto_block_proto_depIdxs,
		MessageInfos:      file_pkg_proto_block_proto_msgTypes,
	}.Build()
	File_pkg_proto_block_proto = out.File
	file_pkg_proto_block_proto_goTypes = nil
	file_pkg_proto_block_proto_depIdxs = nil
}
