// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.0
// source: pkg/proto/p2p.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BlockRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StartHeight   uint64                 `protobuf:"varint,1,opt,name=start_height,json=startHeight,proto3" json:"start_height,omitempty"`
	Limit         uint64                 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlockRequest) Reset() {
	*x = BlockRequest{}
	mi := &file_pkg_proto_p2p_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockRequest) ProtoMessage() {}

func (x *BlockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_p2p_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockRequest.ProtoReflect.Descriptor instead.
func (*BlockRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_p2p_proto_rawDescGZIP(), []int{0}
}

func (x *BlockRequest) GetStartHeight() uint64 {
	if x != nil {
		return x.StartHeight
	}
	return 0
}

func (x *BlockRequest) GetLimit() uint64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type BlockResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Blocks        []*Block               `protobuf:"bytes,1,rep,name=blocks,proto3" json:"blocks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlockResponse) Reset() {
	*x = BlockResponse{}
	mi := &file_pkg_proto_p2p_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockResponse) ProtoMessage() {}

func (x *BlockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_p2p_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockResponse.ProtoReflect.Descriptor instead.
func (*BlockResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_p2p_proto_rawDescGZIP(), []int{1}
}

func (x *BlockResponse) GetBlocks() []*Block {
	if x != nil {
		return x.Blocks
	}
	return nil
}

type KnownTxsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TxIds         []string               `protobuf:"bytes,1,rep,name=tx_ids,json=txIds,proto3" json:"tx_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KnownTxsRequest) Reset() {
	*x = KnownTxsRequest{}
	mi := &file_pkg_proto_p2p_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KnownTxsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KnownTxsRequest) ProtoMessage() {}

func (x *KnownTxsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_p2p_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KnownTxsRequest.ProtoReflect.Descriptor instead.
func (*KnownTxsRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_p2p_proto_rawDescGZIP(), []int{2}
}

func (x *KnownTxsRequest) GetTxIds() []string {
	if x != nil {
		return x.TxIds
	}
	return nil
}

type KnownTxsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KnownTxIds    map[string]bool        `protobuf:"bytes,1,rep,name=known_tx_ids,json=knownTxIds,proto3" json:"known_tx_ids,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KnownTxsResponse) Reset() {
	*x = KnownTxsResponse{}
	mi := &file_pkg_proto_p2p_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KnownTxsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KnownTxsResponse) ProtoMessage() {}

func (x *KnownTxsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_p2p_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KnownTxsResponse.ProtoReflect.Descriptor instead.
func (*KnownTxsResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_p2p_proto_rawDescGZIP(), []int{3}
}

func (x *KnownTxsResponse) GetKnownTxIds() map[string]bool {
	if x != nil {
		return x.KnownTxIds
	}
	return nil
}

type MissingTxsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TxIds         []string               `protobuf:"bytes,1,rep,name=tx_ids,json=txIds,proto3" json:"tx_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MissingTxsRequest) Reset() {
	*x = MissingTxsRequest{}
	mi := &file_pkg_proto_p2p_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MissingTxsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MissingTxsRequest) ProtoMessage() {}

func (x *MissingTxsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_p2p_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MissingTxsRequest.ProtoReflect.Descriptor instead.
func (*MissingTxsRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_p2p_proto_rawDescGZIP(), []int{4}
}

func (x *MissingTxsRequest) GetTxIds() []string {
	if x != nil {
		return x.TxIds
	}
	return nil
}

type MissingTxsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MissingTxs    []*Transaction         `protobuf:"bytes,1,rep,name=missing_txs,json=missingTxs,proto3" json:"missing_txs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MissingTxsResponse) Reset() {
	*x = MissingTxsResponse{}
	mi := &file_pkg_proto_p2p_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MissingTxsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MissingTxsResponse) ProtoMessage() {}

func (x *MissingTxsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_p2p_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MissingTxsResponse.ProtoReflect.Descriptor instead.
func (*MissingTxsResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_p2p_proto_rawDescGZIP(), []int{5}
}

func (x *MissingTxsResponse) GetMissingTxs() []*Transaction {
	if x != nil {
		return x.MissingTxs
	}
	return nil
}

type MempoolSyncRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KnownTxIds    map[string]bool        `protobuf:"bytes,1,rep,name=known_tx_ids,json=knownTxIds,proto3" json:"known_tx_ids,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MempoolSyncRequest) Reset() {
	*x = MempoolSyncRequest{}
	mi := &file_pkg_proto_p2p_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MempoolSyncRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MempoolSyncRequest) ProtoMessage() {}

func (x *MempoolSyncRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_p2p_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MempoolSyncRequest.ProtoReflect.Descriptor instead.
func (*MempoolSyncRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_p2p_proto_rawDescGZIP(), []int{6}
}

func (x *MempoolSyncRequest) GetKnownTxIds() map[string]bool {
	if x != nil {
		return x.KnownTxIds
	}
	return nil
}

type MempoolSyncResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MissingTxs    []*Transaction         `protobuf:"bytes,1,rep,name=missing_txs,json=missingTxs,proto3" json:"missing_txs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MempoolSyncResponse) Reset() {
	*x = MempoolSyncResponse{}
	mi := &file_pkg_proto_p2p_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MempoolSyncResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MempoolSyncResponse) ProtoMessage() {}

func (x *MempoolSyncResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_p2p_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MempoolSyncResponse.ProtoReflect.Descriptor instead.
func (*MempoolSyncResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_p2p_proto_rawDescGZIP(), []int{7}
}

func (x *MempoolSyncResponse) GetMissingTxs() []*Transaction {
	if x != nil {
		return x.MissingTxs
	}
	return nil
}

type ChainTipQuorumCheck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BlockHash     string                 `protobuf:"bytes,1,opt,name=block_hash,json=blockHash,proto3" json:"block_hash,omitempty"`
	BlockHeight   uint64                 `protobuf:"varint,2,opt,name=block_height,json=blockHeight,proto3" json:"block_height,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChainTipQuorumCheck) Reset() {
	*x = ChainTipQuorumCheck{}
	mi := &file_pkg_proto_p2p_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChainTipQuorumCheck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChainTipQuorumCheck) ProtoMessage() {}

func (x *ChainTipQuorumCheck) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_p2p_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChainTipQuorumCheck.ProtoReflect.Descriptor instead.
func (*ChainTipQuorumCheck) Descriptor() ([]byte, []int) {
	return file_pkg_proto_p2p_proto_rawDescGZIP(), []int{8}
}

func (x *ChainTipQuorumCheck) GetBlockHash() string {
	if x != nil {
		return x.BlockHash
	}
	return ""
}

func (x *ChainTipQuorumCheck) GetBlockHeight() uint64 {
	if x != nil {
		return x.BlockHeight
	}
	return 0
}

type NextBlockReady struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BlockHeight   uint64                 `protobuf:"varint,1,opt,name=block_height,json=blockHeight,proto3" json:"block_height,omitempty"`
	ValidatorId   string                 `protobuf:"bytes,2,opt,name=validator_id,json=validatorId,proto3" json:"validator_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NextBlockReady) Reset() {
	*x = NextBlockReady{}
	mi := &file_pkg_proto_p2p_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NextBlockReady) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NextBlockReady) ProtoMessage() {}

func (x *NextBlockReady) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_p2p_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NextBlockReady.ProtoReflect.Descriptor instead.
func (*NextBlockReady) Descriptor() ([]byte, []int) {
	return file_pkg_proto_p2p_proto_rawDescGZIP(), []int{9}
}

func (x *NextBlockReady) GetBlockHeight() uint64 {
	if x != nil {
		return x.BlockHeight
	}
	return 0
}

func (x *NextBlockReady) GetValidatorId() string {
	if x != nil {
		return x.ValidatorId
	}
	return ""
}

type MissingTxRequestByNonce struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Nonce         uint64                 `protobuf:"varint,2,opt,name=nonce,proto3" json:"nonce,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MissingTxRequestByNonce) Reset() {
	*x = MissingTxRequestByNonce{}
	mi := &file_pkg_proto_p2p_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MissingTxRequestByNonce) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MissingTxRequestByNonce) ProtoMessage() {}

func (x *MissingTxRequestByNonce) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_p2p_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MissingTxRequestByNonce.ProtoReflect.Descriptor instead.
func (*MissingTxRequestByNonce) Descriptor() ([]byte, []int) {
	return file_pkg_proto_p2p_proto_rawDescGZIP(), []int{10}
}

func (x *MissingTxRequestByNonce) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *MissingTxRequestByNonce) GetNonce() uint64 {
	if x != nil {
		return x.Nonce
	}
	return 0
}

type FullSyncState struct {
	state           protoimpl.MessageState   `protogen:"open.v1"`
	Accounts        map[string]*AccountState `protobuf:"bytes,1,rep,name=accounts,proto3" json:"accounts,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	ValidatorSet    []*ValidatorInfo         `protobuf:"bytes,2,rep,name=validator_set,json=validatorSet,proto3" json:"validator_set,omitempty"`
	LastBlockHash   string                   `protobuf:"bytes,3,opt,name=last_block_hash,json=lastBlockHash,proto3" json:"last_block_hash,omitempty"`
	LastBlockHeight uint64                   `protobuf:"varint,4,opt,name=last_block_height,json=lastBlockHeight,proto3" json:"last_block_height,omitempty"`
	LastBlock       *Block                   `protobuf:"bytes,5,opt,name=last_block,json=lastBlock,proto3" json:"last_block,omitempty"`
	// --- ADDED FIELDS FOR TOKEN SYNC ---
	Tokens          map[string]*TokenState `protobuf:"bytes,6,rep,name=tokens,proto3" json:"tokens,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	TokenBalances   []*TokenBalance        `protobuf:"bytes,7,rep,name=token_balances,json=tokenBalances,proto3" json:"token_balances,omitempty"`
	TokenAllowances []*TokenAllowance      `protobuf:"bytes,8,rep,name=token_allowances,json=tokenAllowances,proto3" json:"token_allowances,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *FullSyncState) Reset() {
	*x = FullSyncState{}
	mi := &file_pkg_proto_p2p_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FullSyncState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FullSyncState) ProtoMessage() {}

func (x *FullSyncState) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_p2p_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FullSyncState.ProtoReflect.Descriptor instead.
func (*FullSyncState) Descriptor() ([]byte, []int) {
	return file_pkg_proto_p2p_proto_rawDescGZIP(), []int{11}
}

func (x *FullSyncState) GetAccounts() map[string]*AccountState {
	if x != nil {
		return x.Accounts
	}
	return nil
}

func (x *FullSyncState) GetValidatorSet() []*ValidatorInfo {
	if x != nil {
		return x.ValidatorSet
	}
	return nil
}

func (x *FullSyncState) GetLastBlockHash() string {
	if x != nil {
		return x.LastBlockHash
	}
	return ""
}

func (x *FullSyncState) GetLastBlockHeight() uint64 {
	if x != nil {
		return x.LastBlockHeight
	}
	return 0
}

func (x *FullSyncState) GetLastBlock() *Block {
	if x != nil {
		return x.LastBlock
	}
	return nil
}

func (x *FullSyncState) GetTokens() map[string]*TokenState {
	if x != nil {
		return x.Tokens
	}
	return nil
}

func (x *FullSyncState) GetTokenBalances() []*TokenBalance {
	if x != nil {
		return x.TokenBalances
	}
	return nil
}

func (x *FullSyncState) GetTokenAllowances() []*TokenAllowance {
	if x != nil {
		return x.TokenAllowances
	}
	return nil
}

var File_pkg_proto_p2p_proto protoreflect.FileDescriptor

const file_pkg_proto_p2p_proto_rawDesc = "" +
	"\n" +
	"\x13pkg/proto/p2p.proto\x12\x05proto\x1a\x1bpkg/proto/transaction.proto\x1a\x15pkg/proto/block.proto\"G\n" +
	"\fBlockRequest\x12!\n" +
	"\fstart_height\x18\x01 \x01(\x04R\vstartHeight\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x04R\x05limit\"5\n" +
	"\rBlockResponse\x12$\n" +
	"\x06blocks\x18\x01 \x03(\v2\f.proto.BlockR\x06blocks\"(\n" +
	"\x0fKnownTxsRequest\x12\x15\n" +
	"\x06tx_ids\x18\x01 \x03(\tR\x05txIds\"\x9c\x01\n" +
	"\x10KnownTxsResponse\x12I\n" +
	"\fknown_tx_ids\x18\x01 \x03(\v2'.proto.KnownTxsResponse.KnownTxIdsEntryR\n" +
	"knownTxIds\x1a=\n" +
	"\x0fKnownTxIdsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\bR\x05value:\x028\x01\"*\n" +
	"\x11MissingTxsRequest\x12\x15\n" +
	"\x06tx_ids\x18\x01 \x03(\tR\x05txIds\"I\n" +
	"\x12MissingTxsResponse\x123\n" +
	"\vmissing_txs\x18\x01 \x03(\v2\x12.proto.TransactionR\n" +
	"missingTxs\"\xa0\x01\n" +
	"\x12MempoolSyncRequest\x12K\n" +
	"\fknown_tx_ids\x18\x01 \x03(\v2).proto.MempoolSyncRequest.KnownTxIdsEntryR\n" +
	"knownTxIds\x1a=\n" +
	"\x0fKnownTxIdsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\bR\x05value:\x028\x01\"J\n" +
	"\x13MempoolSyncResponse\x123\n" +
	"\vmissing_txs\x18\x01 \x03(\v2\x12.proto.TransactionR\n" +
	"missingTxs\"W\n" +
	"\x13ChainTipQuorumCheck\x12\x1d\n" +
	"\n" +
	"block_hash\x18\x01 \x01(\tR\tblockHash\x12!\n" +
	"\fblock_height\x18\x02 \x01(\x04R\vblockHeight\"V\n" +
	"\x0eNextBlockReady\x12!\n" +
	"\fblock_height\x18\x01 \x01(\x04R\vblockHeight\x12!\n" +
	"\fvalidator_id\x18\x02 \x01(\tR\vvalidatorId\"I\n" +
	"\x17MissingTxRequestByNonce\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\x12\x14\n" +
	"\x05nonce\x18\x02 \x01(\x04R\x05nonce\"\xe3\x04\n" +
	"\rFullSyncState\x12>\n" +
	"\baccounts\x18\x01 \x03(\v2\".proto.FullSyncState.AccountsEntryR\baccounts\x129\n" +
	"\rvalidator_set\x18\x02 \x03(\v2\x14.proto.ValidatorInfoR\fvalidatorSet\x12&\n" +
	"\x0flast_block_hash\x18\x03 \x01(\tR\rlastBlockHash\x12*\n" +
	"\x11last_block_height\x18\x04 \x01(\x04R\x0flastBlockHeight\x12+\n" +
	"\n" +
	"last_block\x18\x05 \x01(\v2\f.proto.BlockR\tlastBlock\x128\n" +
	"\x06tokens\x18\x06 \x03(\v2 .proto.FullSyncState.TokensEntryR\x06tokens\x12:\n" +
	"\x0etoken_balances\x18\a \x03(\v2\x13.proto.TokenBalanceR\rtokenBalances\x12@\n" +
	"\x10token_allowances\x18\b \x03(\v2\x15.proto.TokenAllowanceR\x0ftokenAllowances\x1aP\n" +
	"\rAccountsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12)\n" +
	"\x05value\x18\x02 \x01(\v2\x13.proto.AccountStateR\x05value:\x028\x01\x1aL\n" +
	"\vTokensEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12'\n" +
	"\x05value\x18\x02 \x01(\v2\x11.proto.TokenStateR\x05value:\x028\x01B\x15Z\x13grapthway/pkg/protob\x06proto3"

var (
	file_pkg_proto_p2p_proto_rawDescOnce sync.Once
	file_pkg_proto_p2p_proto_rawDescData []byte
)

func file_pkg_proto_p2p_proto_rawDescGZIP() []byte {
	file_pkg_proto_p2p_proto_rawDescOnce.Do(func() {
		file_pkg_proto_p2p_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_proto_p2p_proto_rawDesc), len(file_pkg_proto_p2p_proto_rawDesc)))
	})
	return file_pkg_proto_p2p_proto_rawDescData
}

var file_pkg_proto_p2p_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_pkg_proto_p2p_proto_goTypes = []any{
	(*BlockRequest)(nil),            // 0: proto.BlockRequest
	(*BlockResponse)(nil),           // 1: proto.BlockResponse
	(*KnownTxsRequest)(nil),         // 2: proto.KnownTxsRequest
	(*KnownTxsResponse)(nil),        // 3: proto.KnownTxsResponse
	(*MissingTxsRequest)(nil),       // 4: proto.MissingTxsRequest
	(*MissingTxsResponse)(nil),      // 5: proto.MissingTxsResponse
	(*MempoolSyncRequest)(nil),      // 6: proto.MempoolSyncRequest
	(*MempoolSyncResponse)(nil),     // 7: proto.MempoolSyncResponse
	(*ChainTipQuorumCheck)(nil),     // 8: proto.ChainTipQuorumCheck
	(*NextBlockReady)(nil),          // 9: proto.NextBlockReady
	(*MissingTxRequestByNonce)(nil), // 10: proto.MissingTxRequestByNonce
	(*FullSyncState)(nil),           // 11: proto.FullSyncState
	nil,                             // 12: proto.KnownTxsResponse.KnownTxIdsEntry
	nil,                             // 13: proto.MempoolSyncRequest.KnownTxIdsEntry
	nil,                             // 14: proto.FullSyncState.AccountsEntry
	nil,                             // 15: proto.FullSyncState.TokensEntry
	(*Block)(nil),                   // 16: proto.Block
	(*Transaction)(nil),             // 17: proto.Transaction
	(*ValidatorInfo)(nil),           // 18: proto.ValidatorInfo
	(*TokenBalance)(nil),            // 19: proto.TokenBalance
	(*TokenAllowance)(nil),          // 20: proto.TokenAllowance
	(*AccountState)(nil),            // 21: proto.AccountState
	(*TokenState)(nil),              // 22: proto.TokenState
}
var file_pkg_proto_p2p_proto_depIdxs = []int32{
	16, // 0: proto.BlockResponse.blocks:type_name -> proto.Block
	12, // 1: proto.KnownTxsResponse.known_tx_ids:type_name -> proto.KnownTxsResponse.KnownTxIdsEntry
	17, // 2: proto.MissingTxsResponse.missing_txs:type_name -> proto.Transaction
	13, // 3: proto.MempoolSyncRequest.known_tx_ids:type_name -> proto.MempoolSyncRequest.KnownTxIdsEntry
	17, // 4: proto.MempoolSyncResponse.missing_txs:type_name -> proto.Transaction
	14, // 5: proto.FullSyncState.accounts:type_name -> proto.FullSyncState.AccountsEntry
	18, // 6: proto.FullSyncState.validator_set:type_name -> proto.ValidatorInfo
	16, // 7: proto.FullSyncState.last_block:type_name -> proto.Block
	15, // 8: proto.FullSyncState.tokens:type_name -> proto.FullSyncState.TokensEntry
	19, // 9: proto.FullSyncState.token_balances:type_name -> proto.TokenBalance
	20, // 10: proto.FullSyncState.token_allowances:type_name -> proto.TokenAllowance
	21, // 11: proto.FullSyncState.AccountsEntry.value:type_name -> proto.AccountState
	22, // 12: proto.FullSyncState.TokensEntry.value:type_name -> proto.TokenState
	13, // [13:13] is the sub-list for method output_type
	13, // [13:13] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_pkg_proto_p2p_proto_init() }
func file_pkg_proto_p2p_proto_init() {
	if File_pkg_proto_p2p_proto != nil {
		return
	}
	file_pkg_proto_transaction_proto_init()
	file_pkg_proto_block_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_proto_p2p_proto_rawDesc), len(file_pkg_proto_p2p_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_proto_p2p_proto_goTypes,
		DependencyIndexes: file_pkg_proto_p2p_proto_depIdxs,
		MessageInfos:      file_pkg_proto_p2p_proto_msgTypes,
	}.Build()
	File_pkg_proto_p2p_proto = out.File
	file_pkg_proto_p2p_proto_goTypes = nil
	file_pkg_proto_p2p_proto_depIdxs = nil
}
