// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.0
// source: pkg/proto/transaction.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TransactionType int32

const (
	TransactionType_TRANSFER           TransactionType = 0
	TransactionType_DEBIT              TransactionType = 1
	TransactionType_REWARD             TransactionType = 2
	TransactionType_GENESIS            TransactionType = 3
	TransactionType_STAKE_DEPOSIT      TransactionType = 4
	TransactionType_STAKE_WITHDRAWAL   TransactionType = 5
	TransactionType_STAKE_ASSIGN       TransactionType = 6
	TransactionType_STAKE_UNASSIGN     TransactionType = 7
	TransactionType_BATCH_AGGREGATION  TransactionType = 8
	TransactionType_SET_ALLOWANCE      TransactionType = 9
	TransactionType_REMOVE_ALLOWANCE   TransactionType = 10
	TransactionType_DELEGATED_TRANSFER TransactionType = 11
	TransactionType_ROLLBACK_DEBIT     TransactionType = 12
	TransactionType_ROLLBACK_CREDIT    TransactionType = 13
	// Token transaction types
	TransactionType_TOKEN_CREATE   TransactionType = 14
	TransactionType_TOKEN_TRANSFER TransactionType = 15
	TransactionType_TOKEN_MINT     TransactionType = 16
	TransactionType_TOKEN_BURN     TransactionType = 17
	TransactionType_TOKEN_APPROVE  TransactionType = 18
	TransactionType_TOKEN_REVOKE   TransactionType = 19
	TransactionType_TOKEN_LOCK     TransactionType = 20
	// Token config transaction types
	TransactionType_TOKEN_CONFIG_BURN TransactionType = 21
	TransactionType_TOKEN_CONFIG_MINT TransactionType = 22
)

// Enum value maps for TransactionType.
var (
	TransactionType_name = map[int32]string{
		0:  "TRANSFER",
		1:  "DEBIT",
		2:  "REWARD",
		3:  "GENESIS",
		4:  "STAKE_DEPOSIT",
		5:  "STAKE_WITHDRAWAL",
		6:  "STAKE_ASSIGN",
		7:  "STAKE_UNASSIGN",
		8:  "BATCH_AGGREGATION",
		9:  "SET_ALLOWANCE",
		10: "REMOVE_ALLOWANCE",
		11: "DELEGATED_TRANSFER",
		12: "ROLLBACK_DEBIT",
		13: "ROLLBACK_CREDIT",
		14: "TOKEN_CREATE",
		15: "TOKEN_TRANSFER",
		16: "TOKEN_MINT",
		17: "TOKEN_BURN",
		18: "TOKEN_APPROVE",
		19: "TOKEN_REVOKE",
		20: "TOKEN_LOCK",
		21: "TOKEN_CONFIG_BURN",
		22: "TOKEN_CONFIG_MINT",
	}
	TransactionType_value = map[string]int32{
		"TRANSFER":           0,
		"DEBIT":              1,
		"REWARD":             2,
		"GENESIS":            3,
		"STAKE_DEPOSIT":      4,
		"STAKE_WITHDRAWAL":   5,
		"STAKE_ASSIGN":       6,
		"STAKE_UNASSIGN":     7,
		"BATCH_AGGREGATION":  8,
		"SET_ALLOWANCE":      9,
		"REMOVE_ALLOWANCE":   10,
		"DELEGATED_TRANSFER": 11,
		"ROLLBACK_DEBIT":     12,
		"ROLLBACK_CREDIT":    13,
		"TOKEN_CREATE":       14,
		"TOKEN_TRANSFER":     15,
		"TOKEN_MINT":         16,
		"TOKEN_BURN":         17,
		"TOKEN_APPROVE":      18,
		"TOKEN_REVOKE":       19,
		"TOKEN_LOCK":         20,
		"TOKEN_CONFIG_BURN":  21,
		"TOKEN_CONFIG_MINT":  22,
	}
)

func (x TransactionType) Enum() *TransactionType {
	p := new(TransactionType)
	*p = x
	return p
}

func (x TransactionType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TransactionType) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_proto_transaction_proto_enumTypes[0].Descriptor()
}

func (TransactionType) Type() protoreflect.EnumType {
	return &file_pkg_proto_transaction_proto_enumTypes[0]
}

func (x TransactionType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TransactionType.Descriptor instead.
func (TransactionType) EnumDescriptor() ([]byte, []int) {
	return file_pkg_proto_transaction_proto_rawDescGZIP(), []int{0}
}

type BatchAggregationPayload struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Debits          map[string]uint64      `protobuf:"bytes,1,rep,name=debits,proto3" json:"debits,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	Rewards         map[string]uint64      `protobuf:"bytes,2,rep,name=rewards,proto3" json:"rewards,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	AggregatedTxIds []string               `protobuf:"bytes,3,rep,name=aggregated_tx_ids,json=aggregatedTxIds,proto3" json:"aggregated_tx_ids,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *BatchAggregationPayload) Reset() {
	*x = BatchAggregationPayload{}
	mi := &file_pkg_proto_transaction_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchAggregationPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchAggregationPayload) ProtoMessage() {}

func (x *BatchAggregationPayload) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_transaction_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchAggregationPayload.ProtoReflect.Descriptor instead.
func (*BatchAggregationPayload) Descriptor() ([]byte, []int) {
	return file_pkg_proto_transaction_proto_rawDescGZIP(), []int{0}
}

func (x *BatchAggregationPayload) GetDebits() map[string]uint64 {
	if x != nil {
		return x.Debits
	}
	return nil
}

func (x *BatchAggregationPayload) GetRewards() map[string]uint64 {
	if x != nil {
		return x.Rewards
	}
	return nil
}

func (x *BatchAggregationPayload) GetAggregatedTxIds() []string {
	if x != nil {
		return x.AggregatedTxIds
	}
	return nil
}

type Transaction struct {
	state          protoimpl.MessageState   `protogen:"open.v1"`
	Id             string                   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type           TransactionType          `protobuf:"varint,2,opt,name=type,proto3,enum=proto.TransactionType" json:"type,omitempty"`
	From           string                   `protobuf:"bytes,3,opt,name=from,proto3" json:"from,omitempty"`
	To             string                   `protobuf:"bytes,4,opt,name=to,proto3" json:"to,omitempty"`
	Amount         uint64                   `protobuf:"varint,5,opt,name=amount,proto3" json:"amount,omitempty"`
	Nonce          uint64                   `protobuf:"varint,6,opt,name=nonce,proto3" json:"nonce,omitempty"`
	Timestamp      *timestamppb.Timestamp   `protobuf:"bytes,7,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	CreatedAt      *timestamppb.Timestamp   `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	TargetNodeId   string                   `protobuf:"bytes,9,opt,name=target_node_id,json=targetNodeId,proto3" json:"target_node_id,omitempty"`
	BatchPayload   *BatchAggregationPayload `protobuf:"bytes,10,opt,name=batch_payload,json=batchPayload,proto3" json:"batch_payload,omitempty"`
	Spender        string                   `protobuf:"bytes,11,opt,name=spender,proto3" json:"spender,omitempty"`
	AllowanceLimit uint64                   `protobuf:"varint,12,opt,name=allowance_limit,json=allowanceLimit,proto3" json:"allowance_limit,omitempty"`
	// Token-specific fields
	TokenAddress  string         `protobuf:"bytes,13,opt,name=token_address,json=tokenAddress,proto3" json:"token_address,omitempty"`
	TokenMetadata *TokenMetadata `protobuf:"bytes,14,opt,name=token_metadata,json=tokenMetadata,proto3" json:"token_metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Transaction) Reset() {
	*x = Transaction{}
	mi := &file_pkg_proto_transaction_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transaction) ProtoMessage() {}

func (x *Transaction) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_transaction_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transaction.ProtoReflect.Descriptor instead.
func (*Transaction) Descriptor() ([]byte, []int) {
	return file_pkg_proto_transaction_proto_rawDescGZIP(), []int{1}
}

func (x *Transaction) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Transaction) GetType() TransactionType {
	if x != nil {
		return x.Type
	}
	return TransactionType_TRANSFER
}

func (x *Transaction) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *Transaction) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *Transaction) GetAmount() uint64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *Transaction) GetNonce() uint64 {
	if x != nil {
		return x.Nonce
	}
	return 0
}

func (x *Transaction) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *Transaction) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Transaction) GetTargetNodeId() string {
	if x != nil {
		return x.TargetNodeId
	}
	return ""
}

func (x *Transaction) GetBatchPayload() *BatchAggregationPayload {
	if x != nil {
		return x.BatchPayload
	}
	return nil
}

func (x *Transaction) GetSpender() string {
	if x != nil {
		return x.Spender
	}
	return ""
}

func (x *Transaction) GetAllowanceLimit() uint64 {
	if x != nil {
		return x.AllowanceLimit
	}
	return 0
}

func (x *Transaction) GetTokenAddress() string {
	if x != nil {
		return x.TokenAddress
	}
	return ""
}

func (x *Transaction) GetTokenMetadata() *TokenMetadata {
	if x != nil {
		return x.TokenMetadata
	}
	return nil
}

type PreValidationVote struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TxId          string                 `protobuf:"bytes,1,opt,name=tx_id,json=txId,proto3" json:"tx_id,omitempty"`
	ValidatorId   string                 `protobuf:"bytes,2,opt,name=validator_id,json=validatorId,proto3" json:"validator_id,omitempty"`
	ValidatorSig  []byte                 `protobuf:"bytes,3,opt,name=validator_sig,json=validatorSig,proto3" json:"validator_sig,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PreValidationVote) Reset() {
	*x = PreValidationVote{}
	mi := &file_pkg_proto_transaction_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PreValidationVote) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PreValidationVote) ProtoMessage() {}

func (x *PreValidationVote) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_transaction_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PreValidationVote.ProtoReflect.Descriptor instead.
func (*PreValidationVote) Descriptor() ([]byte, []int) {
	return file_pkg_proto_transaction_proto_rawDescGZIP(), []int{2}
}

func (x *PreValidationVote) GetTxId() string {
	if x != nil {
		return x.TxId
	}
	return ""
}

func (x *PreValidationVote) GetValidatorId() string {
	if x != nil {
		return x.ValidatorId
	}
	return ""
}

func (x *PreValidationVote) GetValidatorSig() []byte {
	if x != nil {
		return x.ValidatorSig
	}
	return nil
}

type NonceUpdate struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Address         string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	NewPendingNonce uint64                 `protobuf:"varint,2,opt,name=new_pending_nonce,json=newPendingNonce,proto3" json:"new_pending_nonce,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *NonceUpdate) Reset() {
	*x = NonceUpdate{}
	mi := &file_pkg_proto_transaction_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NonceUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NonceUpdate) ProtoMessage() {}

func (x *NonceUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_transaction_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NonceUpdate.ProtoReflect.Descriptor instead.
func (*NonceUpdate) Descriptor() ([]byte, []int) {
	return file_pkg_proto_transaction_proto_rawDescGZIP(), []int{3}
}

func (x *NonceUpdate) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *NonceUpdate) GetNewPendingNonce() uint64 {
	if x != nil {
		return x.NewPendingNonce
	}
	return 0
}

type StakeAllocation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodePeerId    string                 `protobuf:"bytes,1,opt,name=node_peer_id,json=nodePeerId,proto3" json:"node_peer_id,omitempty"`
	Amount        uint64                 `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	LockedAt      *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=locked_at,json=lockedAt,proto3" json:"locked_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StakeAllocation) Reset() {
	*x = StakeAllocation{}
	mi := &file_pkg_proto_transaction_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StakeAllocation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StakeAllocation) ProtoMessage() {}

func (x *StakeAllocation) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_transaction_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StakeAllocation.ProtoReflect.Descriptor instead.
func (*StakeAllocation) Descriptor() ([]byte, []int) {
	return file_pkg_proto_transaction_proto_rawDescGZIP(), []int{4}
}

func (x *StakeAllocation) GetNodePeerId() string {
	if x != nil {
		return x.NodePeerId
	}
	return ""
}

func (x *StakeAllocation) GetAmount() uint64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *StakeAllocation) GetLockedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LockedAt
	}
	return nil
}

type UnbondingStake struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Amount        uint64                 `protobuf:"varint,1,opt,name=amount,proto3" json:"amount,omitempty"`
	UnlockTime    *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=unlock_time,json=unlockTime,proto3" json:"unlock_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnbondingStake) Reset() {
	*x = UnbondingStake{}
	mi := &file_pkg_proto_transaction_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnbondingStake) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnbondingStake) ProtoMessage() {}

func (x *UnbondingStake) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_transaction_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnbondingStake.ProtoReflect.Descriptor instead.
func (*UnbondingStake) Descriptor() ([]byte, []int) {
	return file_pkg_proto_transaction_proto_rawDescGZIP(), []int{5}
}

func (x *UnbondingStake) GetAmount() uint64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *UnbondingStake) GetUnlockTime() *timestamppb.Timestamp {
	if x != nil {
		return x.UnlockTime
	}
	return nil
}

type StakeInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TotalStake    uint64                 `protobuf:"varint,1,opt,name=total_stake,json=totalStake,proto3" json:"total_stake,omitempty"`
	Allocations   []*StakeAllocation     `protobuf:"bytes,2,rep,name=allocations,proto3" json:"allocations,omitempty"`
	Unbonding     []*UnbondingStake      `protobuf:"bytes,3,rep,name=unbonding,proto3" json:"unbonding,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StakeInfo) Reset() {
	*x = StakeInfo{}
	mi := &file_pkg_proto_transaction_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StakeInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StakeInfo) ProtoMessage() {}

func (x *StakeInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_transaction_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StakeInfo.ProtoReflect.Descriptor instead.
func (*StakeInfo) Descriptor() ([]byte, []int) {
	return file_pkg_proto_transaction_proto_rawDescGZIP(), []int{6}
}

func (x *StakeInfo) GetTotalStake() uint64 {
	if x != nil {
		return x.TotalStake
	}
	return 0
}

func (x *StakeInfo) GetAllocations() []*StakeAllocation {
	if x != nil {
		return x.Allocations
	}
	return nil
}

func (x *StakeInfo) GetUnbonding() []*UnbondingStake {
	if x != nil {
		return x.Unbonding
	}
	return nil
}

type AccountState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Balance       uint64                 `protobuf:"varint,2,opt,name=balance,proto3" json:"balance,omitempty"`
	Nonce         uint64                 `protobuf:"varint,3,opt,name=nonce,proto3" json:"nonce,omitempty"`
	PendingNonce  uint64                 `protobuf:"varint,4,opt,name=pending_nonce,json=pendingNonce,proto3" json:"pending_nonce,omitempty"`
	PendingSpend  uint64                 `protobuf:"varint,5,opt,name=pending_spend,json=pendingSpend,proto3" json:"pending_spend,omitempty"`
	StakeInfo     *StakeInfo             `protobuf:"bytes,6,opt,name=stake_info,json=stakeInfo,proto3" json:"stake_info,omitempty"`
	Allowances    map[string]uint64      `protobuf:"bytes,7,rep,name=allowances,proto3" json:"allowances,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccountState) Reset() {
	*x = AccountState{}
	mi := &file_pkg_proto_transaction_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccountState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountState) ProtoMessage() {}

func (x *AccountState) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_transaction_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountState.ProtoReflect.Descriptor instead.
func (*AccountState) Descriptor() ([]byte, []int) {
	return file_pkg_proto_transaction_proto_rawDescGZIP(), []int{7}
}

func (x *AccountState) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *AccountState) GetBalance() uint64 {
	if x != nil {
		return x.Balance
	}
	return 0
}

func (x *AccountState) GetNonce() uint64 {
	if x != nil {
		return x.Nonce
	}
	return 0
}

func (x *AccountState) GetPendingNonce() uint64 {
	if x != nil {
		return x.PendingNonce
	}
	return 0
}

func (x *AccountState) GetPendingSpend() uint64 {
	if x != nil {
		return x.PendingSpend
	}
	return 0
}

func (x *AccountState) GetStakeInfo() *StakeInfo {
	if x != nil {
		return x.StakeInfo
	}
	return nil
}

func (x *AccountState) GetAllowances() map[string]uint64 {
	if x != nil {
		return x.Allowances
	}
	return nil
}

type TransactionList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Transactions  []*Transaction         `protobuf:"bytes,1,rep,name=transactions,proto3" json:"transactions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransactionList) Reset() {
	*x = TransactionList{}
	mi := &file_pkg_proto_transaction_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionList) ProtoMessage() {}

func (x *TransactionList) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_transaction_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionList.ProtoReflect.Descriptor instead.
func (*TransactionList) Descriptor() ([]byte, []int) {
	return file_pkg_proto_transaction_proto_rawDescGZIP(), []int{8}
}

func (x *TransactionList) GetTransactions() []*Transaction {
	if x != nil {
		return x.Transactions
	}
	return nil
}

type TokenMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Ticker        string                 `protobuf:"bytes,2,opt,name=ticker,proto3" json:"ticker,omitempty"`
	Decimals      uint32                 `protobuf:"varint,3,opt,name=decimals,proto3" json:"decimals,omitempty"`
	InitialSupply uint64                 `protobuf:"varint,4,opt,name=initial_supply,json=initialSupply,proto3" json:"initial_supply,omitempty"`
	TokenType     string                 `protobuf:"bytes,5,opt,name=token_type,json=tokenType,proto3" json:"token_type,omitempty"`
	BurnConfig    *BurnConfig            `protobuf:"bytes,6,opt,name=burn_config,json=burnConfig,proto3" json:"burn_config,omitempty"`
	MintConfig    *MintConfig            `protobuf:"bytes,7,opt,name=mint_config,json=mintConfig,proto3" json:"mint_config,omitempty"`
	Metadata      string                 `protobuf:"bytes,8,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TokenMetadata) Reset() {
	*x = TokenMetadata{}
	mi := &file_pkg_proto_transaction_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenMetadata) ProtoMessage() {}

func (x *TokenMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_transaction_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenMetadata.ProtoReflect.Descriptor instead.
func (*TokenMetadata) Descriptor() ([]byte, []int) {
	return file_pkg_proto_transaction_proto_rawDescGZIP(), []int{9}
}

func (x *TokenMetadata) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TokenMetadata) GetTicker() string {
	if x != nil {
		return x.Ticker
	}
	return ""
}

func (x *TokenMetadata) GetDecimals() uint32 {
	if x != nil {
		return x.Decimals
	}
	return 0
}

func (x *TokenMetadata) GetInitialSupply() uint64 {
	if x != nil {
		return x.InitialSupply
	}
	return 0
}

func (x *TokenMetadata) GetTokenType() string {
	if x != nil {
		return x.TokenType
	}
	return ""
}

func (x *TokenMetadata) GetBurnConfig() *BurnConfig {
	if x != nil {
		return x.BurnConfig
	}
	return nil
}

func (x *TokenMetadata) GetMintConfig() *MintConfig {
	if x != nil {
		return x.MintConfig
	}
	return nil
}

func (x *TokenMetadata) GetMetadata() string {
	if x != nil {
		return x.Metadata
	}
	return ""
}

type BurnConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Enabled       bool                   `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	BurnRatePerTx float64                `protobuf:"fixed64,2,opt,name=burn_rate_per_tx,json=burnRatePerTx,proto3" json:"burn_rate_per_tx,omitempty"`
	ManualBurn    bool                   `protobuf:"varint,3,opt,name=manual_burn,json=manualBurn,proto3" json:"manual_burn,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BurnConfig) Reset() {
	*x = BurnConfig{}
	mi := &file_pkg_proto_transaction_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BurnConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BurnConfig) ProtoMessage() {}

func (x *BurnConfig) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_transaction_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BurnConfig.ProtoReflect.Descriptor instead.
func (*BurnConfig) Descriptor() ([]byte, []int) {
	return file_pkg_proto_transaction_proto_rawDescGZIP(), []int{10}
}

func (x *BurnConfig) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *BurnConfig) GetBurnRatePerTx() float64 {
	if x != nil {
		return x.BurnRatePerTx
	}
	return 0
}

func (x *BurnConfig) GetManualBurn() bool {
	if x != nil {
		return x.ManualBurn
	}
	return false
}

type MintConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Enabled       bool                   `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	MintRatePerTx float64                `protobuf:"fixed64,2,opt,name=mint_rate_per_tx,json=mintRatePerTx,proto3" json:"mint_rate_per_tx,omitempty"`
	ManualMint    bool                   `protobuf:"varint,3,opt,name=manual_mint,json=manualMint,proto3" json:"manual_mint,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MintConfig) Reset() {
	*x = MintConfig{}
	mi := &file_pkg_proto_transaction_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MintConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MintConfig) ProtoMessage() {}

func (x *MintConfig) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_transaction_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MintConfig.ProtoReflect.Descriptor instead.
func (*MintConfig) Descriptor() ([]byte, []int) {
	return file_pkg_proto_transaction_proto_rawDescGZIP(), []int{11}
}

func (x *MintConfig) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *MintConfig) GetMintRatePerTx() float64 {
	if x != nil {
		return x.MintRatePerTx
	}
	return 0
}

func (x *MintConfig) GetManualMint() bool {
	if x != nil {
		return x.ManualMint
	}
	return false
}

type TokenState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Ticker        string                 `protobuf:"bytes,3,opt,name=ticker,proto3" json:"ticker,omitempty"`
	Decimals      uint32                 `protobuf:"varint,4,opt,name=decimals,proto3" json:"decimals,omitempty"`
	TotalSupply   uint64                 `protobuf:"varint,5,opt,name=total_supply,json=totalSupply,proto3" json:"total_supply,omitempty"`
	Creator       string                 `protobuf:"bytes,6,opt,name=creator,proto3" json:"creator,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	ConfigLocked  bool                   `protobuf:"varint,8,opt,name=config_locked,json=configLocked,proto3" json:"config_locked,omitempty"`
	InitialSupply uint64                 `protobuf:"varint,9,opt,name=initial_supply,json=initialSupply,proto3" json:"initial_supply,omitempty"`
	TokenType     string                 `protobuf:"bytes,10,opt,name=token_type,json=tokenType,proto3" json:"token_type,omitempty"`
	BurnConfig    *BurnConfig            `protobuf:"bytes,11,opt,name=burn_config,json=burnConfig,proto3" json:"burn_config,omitempty"`
	MintConfig    *MintConfig            `protobuf:"bytes,12,opt,name=mint_config,json=mintConfig,proto3" json:"mint_config,omitempty"`
	Metadata      string                 `protobuf:"bytes,13,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TokenState) Reset() {
	*x = TokenState{}
	mi := &file_pkg_proto_transaction_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenState) ProtoMessage() {}

func (x *TokenState) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_transaction_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenState.ProtoReflect.Descriptor instead.
func (*TokenState) Descriptor() ([]byte, []int) {
	return file_pkg_proto_transaction_proto_rawDescGZIP(), []int{12}
}

func (x *TokenState) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *TokenState) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TokenState) GetTicker() string {
	if x != nil {
		return x.Ticker
	}
	return ""
}

func (x *TokenState) GetDecimals() uint32 {
	if x != nil {
		return x.Decimals
	}
	return 0
}

func (x *TokenState) GetTotalSupply() uint64 {
	if x != nil {
		return x.TotalSupply
	}
	return 0
}

func (x *TokenState) GetCreator() string {
	if x != nil {
		return x.Creator
	}
	return ""
}

func (x *TokenState) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *TokenState) GetConfigLocked() bool {
	if x != nil {
		return x.ConfigLocked
	}
	return false
}

func (x *TokenState) GetInitialSupply() uint64 {
	if x != nil {
		return x.InitialSupply
	}
	return 0
}

func (x *TokenState) GetTokenType() string {
	if x != nil {
		return x.TokenType
	}
	return ""
}

func (x *TokenState) GetBurnConfig() *BurnConfig {
	if x != nil {
		return x.BurnConfig
	}
	return nil
}

func (x *TokenState) GetMintConfig() *MintConfig {
	if x != nil {
		return x.MintConfig
	}
	return nil
}

func (x *TokenState) GetMetadata() string {
	if x != nil {
		return x.Metadata
	}
	return ""
}

type TokenBalance struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TokenAddress  string                 `protobuf:"bytes,1,opt,name=token_address,json=tokenAddress,proto3" json:"token_address,omitempty"`
	Owner         string                 `protobuf:"bytes,2,opt,name=owner,proto3" json:"owner,omitempty"`
	Balance       uint64                 `protobuf:"varint,3,opt,name=balance,proto3" json:"balance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TokenBalance) Reset() {
	*x = TokenBalance{}
	mi := &file_pkg_proto_transaction_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenBalance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenBalance) ProtoMessage() {}

func (x *TokenBalance) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_transaction_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenBalance.ProtoReflect.Descriptor instead.
func (*TokenBalance) Descriptor() ([]byte, []int) {
	return file_pkg_proto_transaction_proto_rawDescGZIP(), []int{13}
}

func (x *TokenBalance) GetTokenAddress() string {
	if x != nil {
		return x.TokenAddress
	}
	return ""
}

func (x *TokenBalance) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *TokenBalance) GetBalance() uint64 {
	if x != nil {
		return x.Balance
	}
	return 0
}

type TokenAllowance struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TokenAddress  string                 `protobuf:"bytes,1,opt,name=token_address,json=tokenAddress,proto3" json:"token_address,omitempty"`
	Owner         string                 `protobuf:"bytes,2,opt,name=owner,proto3" json:"owner,omitempty"`
	Spender       string                 `protobuf:"bytes,3,opt,name=spender,proto3" json:"spender,omitempty"`
	Amount        uint64                 `protobuf:"varint,4,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TokenAllowance) Reset() {
	*x = TokenAllowance{}
	mi := &file_pkg_proto_transaction_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenAllowance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenAllowance) ProtoMessage() {}

func (x *TokenAllowance) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_transaction_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenAllowance.ProtoReflect.Descriptor instead.
func (*TokenAllowance) Descriptor() ([]byte, []int) {
	return file_pkg_proto_transaction_proto_rawDescGZIP(), []int{14}
}

func (x *TokenAllowance) GetTokenAddress() string {
	if x != nil {
		return x.TokenAddress
	}
	return ""
}

func (x *TokenAllowance) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *TokenAllowance) GetSpender() string {
	if x != nil {
		return x.Spender
	}
	return ""
}

func (x *TokenAllowance) GetAmount() uint64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

var File_pkg_proto_transaction_proto protoreflect.FileDescriptor

const file_pkg_proto_transaction_proto_rawDesc = "" +
	"\n" +
	"\x1bpkg/proto/transaction.proto\x12\x05proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xc7\x02\n" +
	"\x17BatchAggregationPayload\x12B\n" +
	"\x06debits\x18\x01 \x03(\v2*.proto.BatchAggregationPayload.DebitsEntryR\x06debits\x12E\n" +
	"\arewards\x18\x02 \x03(\v2+.proto.BatchAggregationPayload.RewardsEntryR\arewards\x12*\n" +
	"\x11aggregated_tx_ids\x18\x03 \x03(\tR\x0faggregatedTxIds\x1a9\n" +
	"\vDebitsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x04R\x05value:\x028\x01\x1a:\n" +
	"\fRewardsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x04R\x05value:\x028\x01\"\xa0\x04\n" +
	"\vTransaction\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12*\n" +
	"\x04type\x18\x02 \x01(\x0e2\x16.proto.TransactionTypeR\x04type\x12\x12\n" +
	"\x04from\x18\x03 \x01(\tR\x04from\x12\x0e\n" +
	"\x02to\x18\x04 \x01(\tR\x02to\x12\x16\n" +
	"\x06amount\x18\x05 \x01(\x04R\x06amount\x12\x14\n" +
	"\x05nonce\x18\x06 \x01(\x04R\x05nonce\x128\n" +
	"\ttimestamp\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12$\n" +
	"\x0etarget_node_id\x18\t \x01(\tR\ftargetNodeId\x12C\n" +
	"\rbatch_payload\x18\n" +
	" \x01(\v2\x1e.proto.BatchAggregationPayloadR\fbatchPayload\x12\x18\n" +
	"\aspender\x18\v \x01(\tR\aspender\x12'\n" +
	"\x0fallowance_limit\x18\f \x01(\x04R\x0eallowanceLimit\x12#\n" +
	"\rtoken_address\x18\r \x01(\tR\ftokenAddress\x12;\n" +
	"\x0etoken_metadata\x18\x0e \x01(\v2\x14.proto.TokenMetadataR\rtokenMetadata\"p\n" +
	"\x11PreValidationVote\x12\x13\n" +
	"\x05tx_id\x18\x01 \x01(\tR\x04txId\x12!\n" +
	"\fvalidator_id\x18\x02 \x01(\tR\vvalidatorId\x12#\n" +
	"\rvalidator_sig\x18\x03 \x01(\fR\fvalidatorSig\"S\n" +
	"\vNonceUpdate\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\x12*\n" +
	"\x11new_pending_nonce\x18\x02 \x01(\x04R\x0fnewPendingNonce\"\x84\x01\n" +
	"\x0fStakeAllocation\x12 \n" +
	"\fnode_peer_id\x18\x01 \x01(\tR\n" +
	"nodePeerId\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x04R\x06amount\x127\n" +
	"\tlocked_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\blockedAt\"e\n" +
	"\x0eUnbondingStake\x12\x16\n" +
	"\x06amount\x18\x01 \x01(\x04R\x06amount\x12;\n" +
	"\vunlock_time\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"unlockTime\"\x9b\x01\n" +
	"\tStakeInfo\x12\x1f\n" +
	"\vtotal_stake\x18\x01 \x01(\x04R\n" +
	"totalStake\x128\n" +
	"\vallocations\x18\x02 \x03(\v2\x16.proto.StakeAllocationR\vallocations\x123\n" +
	"\tunbonding\x18\x03 \x03(\v2\x15.proto.UnbondingStakeR\tunbonding\"\xd7\x02\n" +
	"\fAccountState\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\x12\x18\n" +
	"\abalance\x18\x02 \x01(\x04R\abalance\x12\x14\n" +
	"\x05nonce\x18\x03 \x01(\x04R\x05nonce\x12#\n" +
	"\rpending_nonce\x18\x04 \x01(\x04R\fpendingNonce\x12#\n" +
	"\rpending_spend\x18\x05 \x01(\x04R\fpendingSpend\x12/\n" +
	"\n" +
	"stake_info\x18\x06 \x01(\v2\x10.proto.StakeInfoR\tstakeInfo\x12C\n" +
	"\n" +
	"allowances\x18\a \x03(\v2#.proto.AccountState.AllowancesEntryR\n" +
	"allowances\x1a=\n" +
	"\x0fAllowancesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x04R\x05value:\x028\x01\"I\n" +
	"\x0fTransactionList\x126\n" +
	"\ftransactions\x18\x01 \x03(\v2\x12.proto.TransactionR\ftransactions\"\xa1\x02\n" +
	"\rTokenMetadata\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06ticker\x18\x02 \x01(\tR\x06ticker\x12\x1a\n" +
	"\bdecimals\x18\x03 \x01(\rR\bdecimals\x12%\n" +
	"\x0einitial_supply\x18\x04 \x01(\x04R\rinitialSupply\x12\x1d\n" +
	"\n" +
	"token_type\x18\x05 \x01(\tR\ttokenType\x122\n" +
	"\vburn_config\x18\x06 \x01(\v2\x11.proto.BurnConfigR\n" +
	"burnConfig\x122\n" +
	"\vmint_config\x18\a \x01(\v2\x11.proto.MintConfigR\n" +
	"mintConfig\x12\x1a\n" +
	"\bmetadata\x18\b \x01(\tR\bmetadata\"p\n" +
	"\n" +
	"BurnConfig\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x12'\n" +
	"\x10burn_rate_per_tx\x18\x02 \x01(\x01R\rburnRatePerTx\x12\x1f\n" +
	"\vmanual_burn\x18\x03 \x01(\bR\n" +
	"manualBurn\"p\n" +
	"\n" +
	"MintConfig\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x12'\n" +
	"\x10mint_rate_per_tx\x18\x02 \x01(\x01R\rmintRatePerTx\x12\x1f\n" +
	"\vmanual_mint\x18\x03 \x01(\bR\n" +
	"manualMint\"\xd5\x03\n" +
	"\n" +
	"TokenState\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06ticker\x18\x03 \x01(\tR\x06ticker\x12\x1a\n" +
	"\bdecimals\x18\x04 \x01(\rR\bdecimals\x12!\n" +
	"\ftotal_supply\x18\x05 \x01(\x04R\vtotalSupply\x12\x18\n" +
	"\acreator\x18\x06 \x01(\tR\acreator\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12#\n" +
	"\rconfig_locked\x18\b \x01(\bR\fconfigLocked\x12%\n" +
	"\x0einitial_supply\x18\t \x01(\x04R\rinitialSupply\x12\x1d\n" +
	"\n" +
	"token_type\x18\n" +
	" \x01(\tR\ttokenType\x122\n" +
	"\vburn_config\x18\v \x01(\v2\x11.proto.BurnConfigR\n" +
	"burnConfig\x122\n" +
	"\vmint_config\x18\f \x01(\v2\x11.proto.MintConfigR\n" +
	"mintConfig\x12\x1a\n" +
	"\bmetadata\x18\r \x01(\tR\bmetadata\"c\n" +
	"\fTokenBalance\x12#\n" +
	"\rtoken_address\x18\x01 \x01(\tR\ftokenAddress\x12\x14\n" +
	"\x05owner\x18\x02 \x01(\tR\x05owner\x12\x18\n" +
	"\abalance\x18\x03 \x01(\x04R\abalance\"}\n" +
	"\x0eTokenAllowance\x12#\n" +
	"\rtoken_address\x18\x01 \x01(\tR\ftokenAddress\x12\x14\n" +
	"\x05owner\x18\x02 \x01(\tR\x05owner\x12\x18\n" +
	"\aspender\x18\x03 \x01(\tR\aspender\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\x04R\x06amount*\xbc\x03\n" +
	"\x0fTransactionType\x12\f\n" +
	"\bTRANSFER\x10\x00\x12\t\n" +
	"\x05DEBIT\x10\x01\x12\n" +
	"\n" +
	"\x06REWARD\x10\x02\x12\v\n" +
	"\aGENESIS\x10\x03\x12\x11\n" +
	"\rSTAKE_DEPOSIT\x10\x04\x12\x14\n" +
	"\x10STAKE_WITHDRAWAL\x10\x05\x12\x10\n" +
	"\fSTAKE_ASSIGN\x10\x06\x12\x12\n" +
	"\x0eSTAKE_UNASSIGN\x10\a\x12\x15\n" +
	"\x11BATCH_AGGREGATION\x10\b\x12\x11\n" +
	"\rSET_ALLOWANCE\x10\t\x12\x14\n" +
	"\x10REMOVE_ALLOWANCE\x10\n" +
	"\x12\x16\n" +
	"\x12DELEGATED_TRANSFER\x10\v\x12\x12\n" +
	"\x0eROLLBACK_DEBIT\x10\f\x12\x13\n" +
	"\x0fROLLBACK_CREDIT\x10\r\x12\x10\n" +
	"\fTOKEN_CREATE\x10\x0e\x12\x12\n" +
	"\x0eTOKEN_TRANSFER\x10\x0f\x12\x0e\n" +
	"\n" +
	"TOKEN_MINT\x10\x10\x12\x0e\n" +
	"\n" +
	"TOKEN_BURN\x10\x11\x12\x11\n" +
	"\rTOKEN_APPROVE\x10\x12\x12\x10\n" +
	"\fTOKEN_REVOKE\x10\x13\x12\x0e\n" +
	"\n" +
	"TOKEN_LOCK\x10\x14\x12\x15\n" +
	"\x11TOKEN_CONFIG_BURN\x10\x15\x12\x15\n" +
	"\x11TOKEN_CONFIG_MINT\x10\x16B\x15Z\x13grapthway/pkg/protob\x06proto3"

var (
	file_pkg_proto_transaction_proto_rawDescOnce sync.Once
	file_pkg_proto_transaction_proto_rawDescData []byte
)

func file_pkg_proto_transaction_proto_rawDescGZIP() []byte {
	file_pkg_proto_transaction_proto_rawDescOnce.Do(func() {
		file_pkg_proto_transaction_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_proto_transaction_proto_rawDesc), len(file_pkg_proto_transaction_proto_rawDesc)))
	})
	return file_pkg_proto_transaction_proto_rawDescData
}

var file_pkg_proto_transaction_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pkg_proto_transaction_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_pkg_proto_transaction_proto_goTypes = []any{
	(TransactionType)(0),            // 0: proto.TransactionType
	(*BatchAggregationPayload)(nil), // 1: proto.BatchAggregationPayload
	(*Transaction)(nil),             // 2: proto.Transaction
	(*PreValidationVote)(nil),       // 3: proto.PreValidationVote
	(*NonceUpdate)(nil),             // 4: proto.NonceUpdate
	(*StakeAllocation)(nil),         // 5: proto.StakeAllocation
	(*UnbondingStake)(nil),          // 6: proto.UnbondingStake
	(*StakeInfo)(nil),               // 7: proto.StakeInfo
	(*AccountState)(nil),            // 8: proto.AccountState
	(*TransactionList)(nil),         // 9: proto.TransactionList
	(*TokenMetadata)(nil),           // 10: proto.TokenMetadata
	(*BurnConfig)(nil),              // 11: proto.BurnConfig
	(*MintConfig)(nil),              // 12: proto.MintConfig
	(*TokenState)(nil),              // 13: proto.TokenState
	(*TokenBalance)(nil),            // 14: proto.TokenBalance
	(*TokenAllowance)(nil),          // 15: proto.TokenAllowance
	nil,                             // 16: proto.BatchAggregationPayload.DebitsEntry
	nil,                             // 17: proto.BatchAggregationPayload.RewardsEntry
	nil,                             // 18: proto.AccountState.AllowancesEntry
	(*timestamppb.Timestamp)(nil),   // 19: google.protobuf.Timestamp
}
var file_pkg_proto_transaction_proto_depIdxs = []int32{
	16, // 0: proto.BatchAggregationPayload.debits:type_name -> proto.BatchAggregationPayload.DebitsEntry
	17, // 1: proto.BatchAggregationPayload.rewards:type_name -> proto.BatchAggregationPayload.RewardsEntry
	0,  // 2: proto.Transaction.type:type_name -> proto.TransactionType
	19, // 3: proto.Transaction.timestamp:type_name -> google.protobuf.Timestamp
	19, // 4: proto.Transaction.created_at:type_name -> google.protobuf.Timestamp
	1,  // 5: proto.Transaction.batch_payload:type_name -> proto.BatchAggregationPayload
	10, // 6: proto.Transaction.token_metadata:type_name -> proto.TokenMetadata
	19, // 7: proto.StakeAllocation.locked_at:type_name -> google.protobuf.Timestamp
	19, // 8: proto.UnbondingStake.unlock_time:type_name -> google.protobuf.Timestamp
	5,  // 9: proto.StakeInfo.allocations:type_name -> proto.StakeAllocation
	6,  // 10: proto.StakeInfo.unbonding:type_name -> proto.UnbondingStake
	7,  // 11: proto.AccountState.stake_info:type_name -> proto.StakeInfo
	18, // 12: proto.AccountState.allowances:type_name -> proto.AccountState.AllowancesEntry
	2,  // 13: proto.TransactionList.transactions:type_name -> proto.Transaction
	11, // 14: proto.TokenMetadata.burn_config:type_name -> proto.BurnConfig
	12, // 15: proto.TokenMetadata.mint_config:type_name -> proto.MintConfig
	19, // 16: proto.TokenState.created_at:type_name -> google.protobuf.Timestamp
	11, // 17: proto.TokenState.burn_config:type_name -> proto.BurnConfig
	12, // 18: proto.TokenState.mint_config:type_name -> proto.MintConfig
	19, // [19:19] is the sub-list for method output_type
	19, // [19:19] is the sub-list for method input_type
	19, // [19:19] is the sub-list for extension type_name
	19, // [19:19] is the sub-list for extension extendee
	0,  // [0:19] is the sub-list for field type_name
}

func init() { file_pkg_proto_transaction_proto_init() }
func file_pkg_proto_transaction_proto_init() {
	if File_pkg_proto_transaction_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_proto_transaction_proto_rawDesc), len(file_pkg_proto_transaction_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_proto_transaction_proto_goTypes,
		DependencyIndexes: file_pkg_proto_transaction_proto_depIdxs,
		EnumInfos:         file_pkg_proto_transaction_proto_enumTypes,
		MessageInfos:      file_pkg_proto_transaction_proto_msgTypes,
	}.Build()
	File_pkg_proto_transaction_proto = out.File
	file_pkg_proto_transaction_proto_goTypes = nil
	file_pkg_proto_transaction_proto_depIdxs = nil
}
